M48
; DRILL file KiCad 10.0.3 date 2026-06-10T12:34:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-10T12:34:55+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.450
%
G90
G05
T1
X127.0Y-63.62
T2
X127.0Y-98.74
X143.0Y-68.26
M30
