M48
; DRILL file KiCad 10.0.3 date 2026-06-15T16:25:51
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-15T16:25:51+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X126.0Y-74.0
X126.0Y-139.5
X171.0Y-74.0
X171.0Y-139.5
M30
