M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu22.04.1} date 2026-05-27T21:09:22+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-27T21:09:22+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X164.63Y-77.447
X170.41Y-77.447
M30
