M48
; DRILL file KiCad 10.0.3 date 2026-05-26T11:47:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-26T11:47:44+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.780
%
G90
G05
T1
X145.48Y-95.59
X145.48Y-101.37
T2
X140.97Y-90.882
X140.97Y-106.123
X181.61Y-90.882
X181.61Y-106.123
M30
